protection:
  ## If player has the stablemaster.bypass permission
  ## - true: use owner permission
  ## - false: use player permission
  bypass-as-owner: true
  ## Protection if the owner hurts the horse
  owner-melee: true
  owner-ranged: false
  ## Protection if another player hurts the horse
  player-melee: true
  player-ranged: true