name: ${project.name}
version: ${project.version}
description: ${project.description}
author: nicholosophy
website: ${project.url}
main: net.nperkins.stablemaster.StableMaster



commands:
  stablemaster:
    description: Main stablemaster command
    usage: /<command>
    aliases: [sm]
  smaddrider:
    description: Add a rider to a hourse
    usage: /<command> [player]
  smdelrider:
    description: Remove a rider from a hourse
    usage: /<command> [player]