name: ${project.name}
version: ${project.version}
description: ${project.description}
author: nicholosophy
website: ${project.url}
main: net.nperkins.stablemaster.StableMaster



commands:
  stablemaster:
    description: Stablemaster command
    usage: /<command>
    aliases: [sm]

permissions:
  stablemaster.addrider:
    description: Allows user to add a rider to a horse
    default: true
  stablemaster.delrider:
    description: Allows user to remove a rider from a horse
    default: true
  stablemaster.give:
    description: Allows user to give horse to a new owner
    default: true
  stablemaster.info:
    description: Get info on a horse
    default: true
  stablemaster.rename:
    description: Allows user to rename a horse
    default: op
  stablemaster.teleport:
    description: Allows user to teleport their horse
    default: op
  stablemaster.bypass:
    description: Allows user to interact with all horses
    default: op