name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${author}
authors: [${authors}]
website: ${project.url}
main: net.nperkins.stablemaster.StableMaster

commands:
  stablemaster:
    description: Stablemaster command
    usage: /<command>
    aliases: [sm]

permissions:
  stablemaster.addrider:
    description: Allows user to add a rider to a horse
    default: true
  stablemaster.delrider:
    description: Allows user to remove a rider from a horse
    default: true
  stablemaster.give:
    description: Allows user to give horse to a new owner
    default: true
  stablemaster.help:
    description: Allows user to run the help command
    default: true
  stablemaster.info:
    description: Get info on a horse
    default: true
  stablemaster.rename:
    description: Allows user to rename a horse
    default: op
  stablemaster.rename.colors:
    description: Allows colors in horses names
    default: op
  stablemaster.teleport:
    description: Allows user to teleport their horse
    default: op
  stablemaster.bypass:
    description: Allows user to interact with all horses
    default: op
    children:
      stablemaster.bypass.protection: true
      stablemaster.bypass.ride: true
      stablemaster.bypass.command.addrider: true
      stablemaster.bypass.command.delrider: true
      stablemaster.bypass.command.give: true
      stablemaster.bypass.command.info: true
      stablemaster.bypass.command.rename: true
      stablemaster.bypass.command.teleport: true