name: ${project.name}
version: ${project.version}
description: ${project.description}
author: nicholosophy
website: ${project.url}
main: net.nperkins.stablemaster.StableMaster



commands:
  stablemaster:
    description: Stablemaster command
    usage: /<command>
    aliases: [sm]